# Generated by Django 3.2.13 on 2022-06-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_resort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='desc',
            new_name='desc1',
        ),
    ]
